---
# tasks file for php
# tasks/main.yml
- name: Install PHP packages
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ php_packages }}"

- name: Create PHP file to display hostname
  copy:
    content: "<?php echo website is running on gethostname(); ?>"
    dest: /var/www/html/hostname.php

